image:
  - Visual Studio 2017
  
platform: x64
  
environment:

install:
 - ps: $env:UnsignedArtifact = "streamlabs-overlay-v$env:APPVEYOR_BUILD_NUMBER"


build_script:
  - yarn install 
  - yarn pack

deploy:
  - provider: S3
    access_key_id:
      secure: 80Jl7kcnucSWpDReQ3K6JK/R9vVwnAQYADH2MVSNYts=
    secret_access_key:
      secure: tGpzwrP05lsjPbKNChsVCZUW9d+CCKac08aL1e5nOHhkaOYVgCZxqJDy0J1cV9cd
    bucket: "streamlabs-overlay-binary"
    region: s3-us-east-1
    set_public: true
    artifact: $(UnsignedArtifact).tar.gz
    on:
      appveyor_repo_tag: true

artifacts:
  - path: $(UnsignedArtifact).tar.gz
    name: Distribution Aritfact

test: off